development:
  adapter: postgresql
  database: air_traffic_development
  encoding: utf8
  pool: 5
  timeout: 5000
  username:
  password:


test:
  adapter: postgresql
  database: air_traffic_test
  encoding: utf8
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  database: air_traffic_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: air_trafifc
  password: rjwq1l341ejre
